account = "//div[@id='app']//div[text()='Account']"
sign_up_btn = "//div[@id='app']//button[text()='Login/Signup Now']"
phone_number_field = "//div[@id='portal-root']//div/input[@name='mobileInput']"
submit_btn = "//div[@id='portal-root']//div/button[text()='Submit']"
verify_otp = "//div[@id='portal-root']//button[text()='Verify OTP']"
user_verify = "//div[@id='app']//div[text()='Hi user!']"