add_to_bag = "//div[@id='pdp-bottom-cta-container']//button[text()='Add to Bag']"
view_bag = "//div[@id='pdp-bottom-cta-container']//button[text()='View bag']"
# got_it = ""
proceed_to_buy = "//div[@id='app']//button[text()='Proceed to Buy']"
postal_code = "//div[@id='app']//div/input[@autocomplete='postal-code']"
address_line_1 = "//div[@id='app']//div/label[text()='Address line 1*']"
name = "//div[@id='app']//div/input[@aria-label='Full Name*']"
phone_number = "//div[@id='app']//div/label[text()='Phone Number*']"
move_to_wishlist = "//div[@id='app']//div/button[text()='Move to Wishlist']"
back_shopping = "//div[@id='app']//section/button[text()='Back to shopping']"
wishlist = "//div[@id='app']//div[text()='Wishlist']"
wishlist_verify = "//div[@id='app']//div/h1[text()='My wishlist']"
